import { ClubProfile } from '../types';

export interface DatabaseConfig {
  year: number;
  clubs: ClubProfile[];
}

export const DATABASES: Record<number, DatabaseConfig> = {
  2008: {
    year: 2008,
    clubs: [
      {
        id: 'MUN',
        name: 'Manchester United',
        shortName: 'Man Utd',
        stadium: 'Old Trafford',
        philosophy: 'Youth',
        boardExpectations: 'Win the Premier League and Champions League.',
        fanExpectations: 'Maintain the attacking tradition and youth focus.',
        transferBudget: 60000000,
        wageBudget: 2500000,
        squadStrength: 90,
        academyStrength: 85,
        commercialStrength: 95,
        difficulty: 1,
        primaryColor: '#DA291C',
        secondaryColor: '#000000',
        foundedYear: 1878,
        historicalTrophies: {
          league: 20,
          championsLeague: 3,
          faCup: 13,
          leagueCup: 6
        }
      },
      {
        id: 'CHE',
        name: 'Chelsea',
        shortName: 'Chelsea',
        stadium: 'Stamford Bridge',
        philosophy: 'Balanced',
        boardExpectations: 'Win the Premier League.',
        fanExpectations: 'Consistent success and high-profile signings.',
        transferBudget: 80000000,
        wageBudget: 3000000,
        squadStrength: 89,
        academyStrength: 75,
        commercialStrength: 85,
        difficulty: 1,
        primaryColor: '#034694',
        secondaryColor: '#FFFFFF'
      },
      {
        id: 'ARS',
        name: 'Arsenal',
        shortName: 'Arsenal',
        stadium: 'Emirates Stadium',
        philosophy: 'Attacking',
        boardExpectations: 'Qualify for the Champions League.',
        fanExpectations: 'Beautiful attacking football and youth development.',
        transferBudget: 30000000,
        wageBudget: 1800000,
        squadStrength: 87,
        academyStrength: 90,
        commercialStrength: 80,
        difficulty: 2,
        primaryColor: '#EF0107',
        secondaryColor: '#FFFFFF'
      },
      {
        id: 'LIV',
        name: 'Liverpool',
        shortName: 'Liverpool',
        stadium: 'Anfield',
        philosophy: 'Balanced',
        boardExpectations: 'Challenge for the title.',
        fanExpectations: 'Passion and European success.',
        transferBudget: 40000000,
        wageBudget: 2000000,
        squadStrength: 88,
        academyStrength: 80,
        commercialStrength: 85,
        difficulty: 1,
        primaryColor: '#C8102E',
        secondaryColor: '#F6EB61'
      },
      {
        id: 'TOT',
        name: 'Tottenham Hotspur',
        shortName: 'Spurs',
        stadium: 'White Hart Lane',
        philosophy: 'Attacking',
        boardExpectations: 'Qualify for Europe.',
        fanExpectations: 'Entertaining football.',
        transferBudget: 25000000,
        wageBudget: 1200000,
        squadStrength: 82,
        academyStrength: 78,
        commercialStrength: 75,
        difficulty: 3,
        primaryColor: '#132257',
        secondaryColor: '#FFFFFF'
      },
      {
        id: 'MCI',
        name: 'Manchester City',
        shortName: 'Man City',
        stadium: 'City of Manchester Stadium',
        philosophy: 'Balanced',
        boardExpectations: 'Mid-table stability.',
        fanExpectations: 'Avoid relegation and beat United.',
        transferBudget: 15000000,
        wageBudget: 1000000,
        squadStrength: 78,
        academyStrength: 70,
        commercialStrength: 65,
        difficulty: 4,
        primaryColor: '#6CABDD',
        secondaryColor: '#FFFFFF'
      },
      {
        id: 'EVE',
        name: 'Everton',
        shortName: 'Everton',
        stadium: 'Goodison Park',
        philosophy: 'Defensive',
        boardExpectations: 'Top 8 finish.',
        fanExpectations: 'Hard work and grit.',
        transferBudget: 12000000,
        wageBudget: 900000,
        squadStrength: 81,
        academyStrength: 75,
        commercialStrength: 70,
        difficulty: 3,
        primaryColor: '#003399',
        secondaryColor: '#FFFFFF'
      },
      {
        id: 'NEW',
        name: 'Newcastle United',
        shortName: 'Newcastle',
        stadium: 'St James\' Park',
        philosophy: 'Attacking',
        boardExpectations: 'Top half finish.',
        fanExpectations: 'Exciting football and passion.',
        transferBudget: 20000000,
        wageBudget: 1100000,
        squadStrength: 80,
        academyStrength: 65,
        commercialStrength: 75,
        difficulty: 3,
        primaryColor: '#241F20',
        secondaryColor: '#FFFFFF'
      },
      {
        id: 'AVL',
        name: 'Aston Villa',
        shortName: 'Villa',
        stadium: 'Villa Park',
        philosophy: 'Balanced',
        boardExpectations: 'Top half finish.',
        fanExpectations: 'Progress and stability.',
        transferBudget: 15000000,
        wageBudget: 1000000,
        squadStrength: 80,
        academyStrength: 75,
        commercialStrength: 70,
        difficulty: 3,
        primaryColor: '#670E36',
        secondaryColor: '#95BFE5'
      },
      {
        id: 'WHU',
        name: 'West Ham United',
        shortName: 'West Ham',
        stadium: 'Upton Park',
        philosophy: 'Youth',
        boardExpectations: 'Mid-table finish.',
        fanExpectations: 'The West Ham way (attacking football).',
        transferBudget: 12000000,
        wageBudget: 900000,
        squadStrength: 79,
        academyStrength: 82,
        commercialStrength: 70,
        difficulty: 3,
        primaryColor: '#7A263A',
        secondaryColor: '#1BB1E7'
      },
      {
        id: 'POR',
        name: 'Portsmouth',
        shortName: 'Pompey',
        stadium: 'Fratton Park',
        philosophy: 'Balanced',
        boardExpectations: 'Top half finish.',
        fanExpectations: 'Cup runs and passion.',
        transferBudget: 10000000,
        wageBudget: 850000,
        squadStrength: 80,
        academyStrength: 60,
        commercialStrength: 65,
        difficulty: 3,
        primaryColor: '#0000FF',
        secondaryColor: '#FFFFFF'
      },
      {
        id: 'BLA',
        name: 'Blackburn Rovers',
        shortName: 'Blackburn',
        stadium: 'Ewood Park',
        philosophy: 'Balanced',
        boardExpectations: 'Top half finish.',
        fanExpectations: 'Consistency.',
        transferBudget: 8000000,
        wageBudget: 750000,
        squadStrength: 79,
        academyStrength: 70,
        commercialStrength: 60,
        difficulty: 3,
        primaryColor: '#0000FF',
        secondaryColor: '#FFFFFF'
      },
      {
        id: 'MID',
        name: 'Middlesbrough',
        shortName: 'Boro',
        stadium: 'Riverside Stadium',
        philosophy: 'Youth',
        boardExpectations: 'Mid-table finish.',
        fanExpectations: 'Local talent development.',
        transferBudget: 7000000,
        wageBudget: 700000,
        squadStrength: 78,
        academyStrength: 80,
        commercialStrength: 60,
        difficulty: 4,
        primaryColor: '#E21B23',
        secondaryColor: '#FFFFFF'
      },
      {
        id: 'WIG',
        name: 'Wigan Athletic',
        shortName: 'Wigan',
        stadium: 'JJB Stadium',
        philosophy: 'Balanced',
        boardExpectations: 'Avoid relegation.',
        fanExpectations: 'Survival.',
        transferBudget: 5000000,
        wageBudget: 500000,
        squadStrength: 75,
        academyStrength: 55,
        commercialStrength: 50,
        difficulty: 5,
        primaryColor: '#0000FF',
        secondaryColor: '#FFFFFF'
      },
      {
        id: 'SUN',
        name: 'Sunderland',
        shortName: 'Sunderland',
        stadium: 'Stadium of Light',
        philosophy: 'Balanced',
        boardExpectations: 'Avoid relegation.',
        fanExpectations: 'Passion and survival.',
        transferBudget: 10000000,
        wageBudget: 700000,
        squadStrength: 76,
        academyStrength: 65,
        commercialStrength: 65,
        difficulty: 4,
        primaryColor: '#FF0000',
        secondaryColor: '#FFFFFF'
      },
      {
        id: 'BOL',
        name: 'Bolton Wanderers',
        shortName: 'Bolton',
        stadium: 'Reebok Stadium',
        philosophy: 'Defensive',
        boardExpectations: 'Mid-table finish.',
        fanExpectations: 'Hard to beat.',
        transferBudget: 6000000,
        wageBudget: 650000,
        squadStrength: 77,
        academyStrength: 60,
        commercialStrength: 60,
        difficulty: 4,
        primaryColor: '#FFFFFF',
        secondaryColor: '#0000FF'
      },
      {
        id: 'FUL',
        name: 'Fulham',
        shortName: 'Fulham',
        stadium: 'Craven Cottage',
        philosophy: 'Balanced',
        boardExpectations: 'Avoid relegation.',
        fanExpectations: 'Survival.',
        transferBudget: 8000000,
        wageBudget: 700000,
        squadStrength: 76,
        academyStrength: 65,
        commercialStrength: 65,
        difficulty: 4,
        primaryColor: '#FFFFFF',
        secondaryColor: '#000000'
      },
      {
        id: 'REA',
        name: 'Reading',
        shortName: 'Reading',
        stadium: 'Madejski Stadium',
        philosophy: 'Balanced',
        boardExpectations: 'Avoid relegation.',
        fanExpectations: 'Survival.',
        transferBudget: 4000000,
        wageBudget: 450000,
        squadStrength: 75,
        academyStrength: 60,
        commercialStrength: 55,
        difficulty: 5,
        primaryColor: '#0000FF',
        secondaryColor: '#FFFFFF'
      },
      {
        id: 'BIR',
        name: 'Birmingham City',
        shortName: 'Birmingham',
        stadium: 'St Andrew\'s',
        philosophy: 'Balanced',
        boardExpectations: 'Avoid relegation.',
        fanExpectations: 'Survival.',
        transferBudget: 5000000,
        wageBudget: 500000,
        squadStrength: 75,
        academyStrength: 60,
        commercialStrength: 60,
        difficulty: 5,
        primaryColor: '#0000FF',
        secondaryColor: '#FFFFFF'
      },
      {
        id: 'DER',
        name: 'Derby County',
        shortName: 'Derby',
        stadium: 'Pride Park',
        philosophy: 'Balanced',
        boardExpectations: 'Avoid relegation.',
        fanExpectations: 'Survival.',
        transferBudget: 3000000,
        wageBudget: 400000,
        squadStrength: 72,
        academyStrength: 55,
        commercialStrength: 55,
        difficulty: 5,
        primaryColor: '#FFFFFF',
        secondaryColor: '#000000'
      }
    ]
  },
  2025: {
    year: 2025,
    clubs: [
      {
        id: 'MCI',
        name: 'Manchester City',
        shortName: 'Man City',
        stadium: 'Etihad Stadium',
        philosophy: 'Attacking',
        boardExpectations: 'Win the Premier League.',
        fanExpectations: 'Dominance and beautiful football.',
        transferBudget: 150000000,
        wageBudget: 5000000,
        squadStrength: 92,
        academyStrength: 85,
        commercialStrength: 95,
        difficulty: 1,
        primaryColor: '#6CABDD',
        secondaryColor: '#FFFFFF'
      },
      {
        id: 'ARS',
        name: 'Arsenal',
        shortName: 'Arsenal',
        stadium: 'Emirates Stadium',
        philosophy: 'Attacking',
        boardExpectations: 'Win the Premier League.',
        fanExpectations: 'Title challenge and attractive football.',
        transferBudget: 100000000,
        wageBudget: 4000000,
        squadStrength: 90,
        academyStrength: 88,
        commercialStrength: 90,
        difficulty: 1,
        primaryColor: '#EF0107',
        secondaryColor: '#FFFFFF'
      },
      {
        id: 'LIV',
        name: 'Liverpool',
        shortName: 'Liverpool',
        stadium: 'Anfield',
        philosophy: 'Attacking',
        boardExpectations: 'Challenge for the title.',
        fanExpectations: 'High-intensity football and success.',
        transferBudget: 80000000,
        wageBudget: 4200000,
        squadStrength: 89,
        academyStrength: 85,
        commercialStrength: 92,
        difficulty: 1,
        primaryColor: '#C8102E',
        secondaryColor: '#F6EB61'
      },
      {
        id: 'AVL',
        name: 'Aston Villa',
        shortName: 'Villa',
        stadium: 'Villa Park',
        philosophy: 'Balanced',
        boardExpectations: 'Qualify for the Champions League.',
        fanExpectations: 'Progress and European nights.',
        transferBudget: 60000000,
        wageBudget: 2800000,
        squadStrength: 86,
        academyStrength: 80,
        commercialStrength: 80,
        difficulty: 2,
        primaryColor: '#670E36',
        secondaryColor: '#95BFE5'
      },
      {
        id: 'TOT',
        name: 'Tottenham Hotspur',
        shortName: 'Spurs',
        stadium: 'Tottenham Hotspur Stadium',
        philosophy: 'Attacking',
        boardExpectations: 'Top 4 finish.',
        fanExpectations: 'Entertaining football and a trophy.',
        transferBudget: 70000000,
        wageBudget: 3500000,
        squadStrength: 87,
        academyStrength: 82,
        commercialStrength: 88,
        difficulty: 2,
        primaryColor: '#132257',
        secondaryColor: '#FFFFFF'
      },
      {
        id: 'CHE',
        name: 'Chelsea',
        shortName: 'Chelsea',
        stadium: 'Stamford Bridge',
        philosophy: 'Youth',
        boardExpectations: 'Qualify for the Champions League.',
        fanExpectations: 'Success with the new project.',
        transferBudget: 120000000,
        wageBudget: 4500000,
        squadStrength: 88,
        academyStrength: 90,
        commercialStrength: 90,
        difficulty: 2,
        primaryColor: '#034694',
        secondaryColor: '#FFFFFF'
      },
      {
        id: 'NEW',
        name: 'Newcastle United',
        shortName: 'Newcastle',
        stadium: 'St James\' Park',
        philosophy: 'Balanced',
        boardExpectations: 'Qualify for Europe.',
        fanExpectations: 'Ambition and progress.',
        transferBudget: 80000000,
        wageBudget: 3000000,
        squadStrength: 85,
        academyStrength: 75,
        commercialStrength: 82,
        difficulty: 2,
        primaryColor: '#241F20',
        secondaryColor: '#FFFFFF'
      },
      {
        id: 'MUN',
        name: 'Manchester United',
        shortName: 'Man Utd',
        stadium: 'Old Trafford',
        philosophy: 'Youth',
        boardExpectations: 'Top 4 finish.',
        fanExpectations: 'Return to the top and youth focus.',
        transferBudget: 100000000,
        wageBudget: 4800000,
        squadStrength: 87,
        academyStrength: 88,
        commercialStrength: 95,
        difficulty: 2,
        primaryColor: '#DA291C',
        secondaryColor: '#000000'
      },
      {
        id: 'WHU',
        name: 'West Ham United',
        shortName: 'West Ham',
        stadium: 'London Stadium',
        philosophy: 'Balanced',
        boardExpectations: 'Top 8 finish.',
        fanExpectations: 'European football.',
        transferBudget: 50000000,
        wageBudget: 2200000,
        squadStrength: 83,
        academyStrength: 78,
        commercialStrength: 78,
        difficulty: 3,
        primaryColor: '#7A263A',
        secondaryColor: '#1BB1E7'
      },
      {
        id: 'CRY',
        name: 'Crystal Palace',
        shortName: 'Palace',
        stadium: 'Selhurst Park',
        philosophy: 'Attacking',
        boardExpectations: 'Top half finish.',
        fanExpectations: 'Exciting football.',
        transferBudget: 30000000,
        wageBudget: 1500000,
        squadStrength: 81,
        academyStrength: 80,
        commercialStrength: 70,
        difficulty: 3,
        primaryColor: '#1B458F',
        secondaryColor: '#C4122E'
      },
      {
        id: 'BHA',
        name: 'Brighton & Hove Albion',
        shortName: 'Brighton',
        stadium: 'Amex Stadium',
        philosophy: 'Youth',
        boardExpectations: 'Top half finish.',
        fanExpectations: 'Smart recruitment and progress.',
        transferBudget: 40000000,
        wageBudget: 1800000,
        squadStrength: 82,
        academyStrength: 85,
        commercialStrength: 75,
        difficulty: 3,
        primaryColor: '#0057B8',
        secondaryColor: '#FFFFFF'
      },
      {
        id: 'BOU',
        name: 'Bournemouth',
        shortName: 'Bournemouth',
        stadium: 'Vitality Stadium',
        philosophy: 'Balanced',
        boardExpectations: 'Mid-table finish.',
        fanExpectations: 'Stability.',
        transferBudget: 25000000,
        wageBudget: 1200000,
        squadStrength: 80,
        academyStrength: 70,
        commercialStrength: 65,
        difficulty: 4,
        primaryColor: '#DA291C',
        secondaryColor: '#000000'
      },
      {
        id: 'FUL',
        name: 'Fulham',
        shortName: 'Fulham',
        stadium: 'Craven Cottage',
        philosophy: 'Balanced',
        boardExpectations: 'Mid-table finish.',
        fanExpectations: 'Stability.',
        transferBudget: 30000000,
        wageBudget: 1600000,
        squadStrength: 81,
        academyStrength: 75,
        commercialStrength: 72,
        difficulty: 3,
        primaryColor: '#FFFFFF',
        secondaryColor: '#000000'
      },
      {
        id: 'WOL',
        name: 'Wolves',
        shortName: 'Wolves',
        stadium: 'Molineux Stadium',
        philosophy: 'Balanced',
        boardExpectations: 'Mid-table finish.',
        fanExpectations: 'Progress.',
        transferBudget: 25000000,
        wageBudget: 1400000,
        squadStrength: 80,
        academyStrength: 75,
        commercialStrength: 70,
        difficulty: 4,
        primaryColor: '#FDB913',
        secondaryColor: '#231F20'
      },
      {
        id: 'EVE',
        name: 'Everton',
        shortName: 'Everton',
        stadium: 'Goodison Park',
        philosophy: 'Defensive',
        boardExpectations: 'Avoid relegation.',
        fanExpectations: 'Survival and move to new stadium.',
        transferBudget: 15000000,
        wageBudget: 1800000,
        squadStrength: 79,
        academyStrength: 75,
        commercialStrength: 75,
        difficulty: 4,
        primaryColor: '#003399',
        secondaryColor: '#FFFFFF'
      },
      {
        id: 'BRE',
        name: 'Brentford',
        shortName: 'Brentford',
        stadium: 'Gtech Community Stadium',
        philosophy: 'Balanced',
        boardExpectations: 'Mid-table finish.',
        fanExpectations: 'Smart football.',
        transferBudget: 20000000,
        wageBudget: 1100000,
        squadStrength: 80,
        academyStrength: 70,
        commercialStrength: 68,
        difficulty: 4,
        primaryColor: '#E30613',
        secondaryColor: '#FFFFFF'
      },
      {
        id: 'NFO',
        name: 'Nottingham Forest',
        shortName: 'Forest',
        stadium: 'City Ground',
        philosophy: 'Balanced',
        boardExpectations: 'Avoid relegation.',
        fanExpectations: 'Survival.',
        transferBudget: 30000000,
        wageBudget: 1600000,
        squadStrength: 79,
        academyStrength: 72,
        commercialStrength: 70,
        difficulty: 4,
        primaryColor: '#DD0000',
        secondaryColor: '#FFFFFF'
      },
      {
        id: 'LEI',
        name: 'Leicester City',
        shortName: 'Leicester',
        stadium: 'King Power Stadium',
        philosophy: 'Balanced',
        boardExpectations: 'Avoid relegation.',
        fanExpectations: 'Survival.',
        transferBudget: 15000000,
        wageBudget: 1400000,
        squadStrength: 78,
        academyStrength: 75,
        commercialStrength: 75,
        difficulty: 4,
        primaryColor: '#003090',
        secondaryColor: '#FDBE11'
      },
      {
        id: 'IPS',
        name: 'Ipswich Town',
        shortName: 'Ipswich',
        stadium: 'Portman Road',
        philosophy: 'Balanced',
        boardExpectations: 'Avoid relegation.',
        fanExpectations: 'Survival.',
        transferBudget: 10000000,
        wageBudget: 800000,
        squadStrength: 76,
        academyStrength: 70,
        commercialStrength: 65,
        difficulty: 5,
        primaryColor: '#0000FF',
        secondaryColor: '#FFFFFF'
      },
      {
        id: 'SOU',
        name: 'Southampton',
        shortName: 'Southampton',
        stadium: 'St Mary\'s Stadium',
        philosophy: 'Youth',
        boardExpectations: 'Avoid relegation.',
        fanExpectations: 'Survival and youth development.',
        transferBudget: 12000000,
        wageBudget: 1000000,
        squadStrength: 77,
        academyStrength: 82,
        commercialStrength: 70,
        difficulty: 5,
        primaryColor: '#D71920',
        secondaryColor: '#130C0E'
      }
    ]
  }
};
